language: generic
env:
  global:
    - IDE_VERSION=1.8.5
  matrix:
    - BOARD="arduino:avr:uno"
before_install:
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - buildExampleSketch() { arduino --verbose-build --verify --board $BOARD $PWD/examples/$1/$1.ino; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/CAN
script:
  - buildExampleSketch CANReceiver
  - buildExampleSketch CANReceiverCallback
  - buildExampleSketch CANSender
